export const CLICK_READING_PROGRESS = "CLICK_READING_PROGRESS";
export const TOGGLE_TOC="TOGGLE_TOC"
export const TOGGLE_MORE_VIEW="TOGGLE_MORE_VIEW"
export const CHANGE_READING_PROGRESS="CHANGE_READING_PROGRESS"
export const GOTO_READING_PROGRESS="GOTO_READING_PROGRESS"
export const CHANGE_CHAPTER ="CHANGE_CHAPTER"
export const LOADING_EBOOK_REQUESTED ="LOADING_EBOOK_REQUESTED"
export const LOADING_EBOOK_SUCCEEDED ="LOADING_EBOOK_SUCCEEDED"
export const LOADING_EBOOK_FAILED ="LOADING_EBOOK_FAILED"

export const RENDERER_LOCATION_CHANGED="RENDERER_LOCATION_CHANGED"
export const SELECT_EBOOK ="SELECT_EBOOK"
